export { default as About } from './about/about';
export { default as Navbar } from './navbar/navbar';
export { default as Tags } from './tags/tags';
export { default as Results } from './results/results';
export { default as Support } from './support/support';
export { default as Calendar } from './calendar/calendar';
export { default as Loader } from './loader/loader';
export { default as eventForm } from './eventHandler/eventForm'
export { default as login } from './login/Login'
